version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/rails_app
    depends_on:
      - db
    command: ["rails", "s", "-b", "0.0.0.0"]
  db:
    image: postgres:10.3
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
    driver: local
